movit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from pages.views import Home

urlpatterns = [
    url(r'^gestion/', admin.site.urls),
    url(r'^$', Home.as_view(), name="home"),
    url(r'^pages/', include('pages.urls', namespace="pages")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #For dev purpose only

pages/urls.py
from django.conf.urls import url, include
from pages.views import ProductionList, VideoView, TeamView, ArticleView, PageView, ArticleDetailView, credit

urlpatterns = [
    url(r'^prod/(?P<pk>\d+)$', ProductionList.as_view(), name="prod"),
    url(r'^prod/(?P<pk>\d+)/(?P<page>\d+)$', ProductionList.as_view(), name="prod-page"),
    url(r'^video/(?P<pk>\d+)$', VideoView.as_view(), name="video"),
    url(r'^blog-detail/(?P<pk>\d+)$', ArticleDetailView.as_view(), name="blog_detail"),
    url(r'^blog/$', ArticleView.as_view(), name="blog"),
    url(r'^page/(?P<pk>\d+)$', PageView.as_view(), name="page"),
    url(r'^team/(?P<pk>\d+)$', TeamView.as_view(), name="specific-team"),
    url(r'^team/$', TeamView.as_view(), name="team"),
    url(r'^credit/$', credit , name="credit"),
]

pages/templates/pages/article.html
{% extends "pages/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
    Articles
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/article.css' %}">
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="container">
        {% for piece_of_news in news %}
        <div class="row article">
            <div class="col-md-12 text-centered">
                <h2 class="title"><a href="{% url 'pages:blog_detail' piece_of_news.id %}">{{piece_of_news.title}}</a></h2>
            </div>
            <div class="col-md-12 text">
                <p class="date" >{% trans "Mise en ligne le " %}{{piece_of_news.date|date:"d M Y"}}{% trans " à " %}{{piece_of_news.date|date:"H:m"}} par {{piece_of_news.author}}</p>
                <p>{{piece_of_news.content|safe}}</p>
            </div>
        </div>
        {% endfor %}
        {% if page_obj.has_next or page_obj.has_previous %}
        <div class="row margin-top margin-bottom">
            <div class="col-md-12 text">
                {% if page_obj.has_previous %} <a href="{% url 'pages:blog'%}?page={{page_obj.previous_page_number}}" class="nav-link-pagin"><span class="fa fa-chevron-circle-left"></span> {% trans "Précédent" %}</a> {% endif %}
                {% if page_obj.has_next %} <a href="{% url 'pages:blog'%}?page={{page_obj.next_page_number}}" class="nav-link-pagin" style="float: right">{% trans "Suivant" %} <span class="fa fa-chevron-circle-right"></span></a> {% endif %}
            </div>
        </div>
        {% else %}
        <div class="row margin-bottom">

        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

pages/templates/pages/article_detail.html
{% extends "pages/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
    Articles
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/article.css' %}">
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="container">
        <div class="row article">
            <div class="col-md-12 text-centered">
                <h2 class="title">{{news.title}}</h2>
            </div>
            <div class="col-md-12 text">
                <p class="date" >{% trans "Mise en ligne le " %}{{news.date|date:"d M Y"}}{% trans " à " %}{{news.date|date:"H:m"}} par {{news.author}}</p>
                <p>{{news.content|safe}}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

pages/templates/pages/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/base.css'%}">
        <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css'%}">
        {% block css %}{% endblock %}
     </head>
  <body>
      <ul class="navigation">
          <li id="menu-button"> <a href="#" onclick="toggleMenu();"><span class="fa fa-bars"></span></a></li>
          <li class="logo-wrapper"><a href="{% url 'home' %}" style="display:inline"><img src="{% static 'image/movit-rec.png' %}" alt="Movit" class="movit-logo"></a></li>
          <li class="nav-link"><a href="{% url 'home' %}"><span class="fa fa-home"></span> {% trans "Accueil" %}</a></li>
          <li class="nav-link"><a href="{% url 'pages:blog' %}"><span class="fa fa-futbol-o"></span> {% trans "Accueil élèves" %}</a></li>
          {% for production in productions %}
          <li class="nav-link"><a href="{% url 'pages:prod' production.id %}"><span class="fa {{production.fa_icon}}"></span> {{production.name}} </a></li>
          {% endfor %}
          <li class="nav-link"><a href="{{garbage_url}}"><span class="fa fa-file-video-o"></span> {% trans "Les rushs" %}</a></li>
          <li class="nav-link"><a href="{% url 'pages:team' %}"><span class="fa fa-users"></span> {% trans "L' équipe" %}</a></li>
          {% for page in pages %}
          <li class="nav-link"><a href="{% url 'pages:page' page.id %}"><span class="fa {{page.fa_icon}}"></span> {{page.title}} </a></li>
          {% endfor %}
      </ul>
      {% block content %}{% endblock %}
      <footer class="text-centered" id="footer">
          <p class="footer-text">Movi't 2017 - Tous droits résrvés</p>
      </footer>

      <script type="text/javascript" src="{% static 'js/jquery.min.js'%}"></script>
      <script type="text/javascript">
      $(window).on('load resize scroll', function() {
          var f = $('#footer');
          f.css({position:'static'});
          if (f.offset().top + f.height() < $(window).height()) {
              f.css({position:'fixed', bottom:'0', opacity:'1'});
          }else {
              f.css({opacity:'1'});
          }
      });
      </script>
      <script type="text/javascript">
          $( document ).ready(function() {
              if ($(document).width() < 992) {
                  var elements = document.getElementsByClassName("nav-link");
                  for (i=0; i<elements.length; i++) {
                      elements[i].setAttribute('style', 'display:none !important');
                  };
              };
          });
          function toggleMenu() {
              var elements = document.getElementsByClassName("nav-link");
              for (i=0; i<elements.length; i++) {
                  if (elements[i].style.display == "block") {
                      elements[i].style.display = "none";
                  } else {
                      elements[i].setAttribute('style', 'display:block !important');
                  };
              };
          }
      </script>
      {% block javascript %}{% endblock %}
  </body>
</html>

pages/templates/pages/home.html
{% extends "pages/base.html" %}
{% load static %}
{% load i18n %}

 {% block title %}
    Movi't Accueil
 {% endblock %}

 {% block css %}
    <link rel="stylesheet" href="{% static 'css/home.css'%}">
 {% endblock %}

 {% block content %}
 <div class="intro-panel">
     <video class="vid" autoplay="true" loop="true">
         <source src="{% static 'video/bg-video-croped.mp4'%}" type='video/mp4'>
     </video>
     <div class="video-link text-centered">
         <a href="{{video_link}}">
             <img src="{% static 'image/play.png' %}" alt="play">
             DÉCOUVREZ NOUS
         </a>
     </div>
     <div class="container larger-container margin-top larger-container">
         <div class="row">
             <div class="col-md-6 intro margin-bottom">
                 <h2 class="text-centered intro-title">Le mot de l'équipe</h2>
                 <p><span class="tabulation">Nous vous souhaitons la bienvenue sur le site du <span class="bold">Movi't, le club vidéo de L'IMT Atlantique</span>. Nous sommes des étudiants de tous horizons qui se réunissent grâce à notre passion de l'écriture, la production et la réalisation audiovisuelle. </p>
                 <p><span class="tabulation">Nous filmons les évènements de la vie sur le campus comme les soirées, les tournois sportifs ou les activités des clubs et associations. Mais nous sortons aussi régulièrement du campus à l’occasion de spectacles ou de sorties liées à la vie étudiante. </p>
                 <p><span class="tabulation">Nous recherchons des membres intéressés par divers aspects de l’audiovisuel. Que ce soit la réalisation, la production ou juste l’écriture, nous vous accueillons donc à bras ouverts!</p>
             </div>
         </div>
     </div>
 </div>
 <div class="realisation">
     <div class="container">
         <div class="row">
             <div class="col-md-offset-6 col-md-6 margin-top margin-bottom">
                 <h2 class="text-centered intro-title">Nos réalisations</h2><hr />
                 <span class="bigger-text">
                     <p><span class="tabulation">Notre activité principale est la production du QHT: "Quart d'heure Télécom". C'est une sorte de "best-of" de la vie étudiante de plus d'un quart d'heure qui sort tous les mois.<br />On y retrouve également des sketchs écrits par les élèves et des interventions des clubs et associations.</p>
                     <p><span class="tabulation">Nous travaillons également sur un nouveau concept: Le Teubreux déchainé. Dans cette émission, nous cherchons à donner la parole aux étudiants pour qu'ils nous parlent de ce qui les intéresse.</p>
                     <p><span class="tabulation">Enfin, nous réalison des vidéos avec les étudiants pour des projets liés à l'école ou personnels.</p>
                 </span>
             </div>
         </div>
     </div>
 </div>
 <div class="home-message margin-top">
     <div class="container">
        <div class="row">
             <div class="col-md-offset-2 col-md-8">
                 <h2 class="text-centered intro-title">{% trans "Les remarques d’ordre pratique" %}</h2><hr>
                 <p class="bold">Comment accéder à notre contenu ?</p>
                 <p><span class="tabulation"></span>Si vous êtes élève ou ancien élève, vous pouvez accéder à l'ensemble de notre contenu en vous connectant avec votre compte Resel. Les autres visiteurs n’ont accès qu’au contenu publique. Vous ne parvenez pas à vous connecter ? Contacter le Resel.</p>
	             <p class="bold">Puis-je diffuser le contenu présent sur le site ?</p>
	             <p><span class="tabulation"></span>Désolé, mais il est interdit de diffuser les images (photo ou vidéo) du Movi't sans l'autorisation des personnes dont le droit à l'image est en jeu, des personnes ayant produit les images et du club. </p>
	             <p class="bold">Je ne souhaite pas apparaitre dans les émissions du Movi’t, puis-je faire quelque chose ?</p>
                 <p><span class="tabulation"></span>Nous prêtons une grande importance au droit à l’image et tout contenu vous représentant peut être modifié ou supprimé à votre demande. </p>
             </div>
        </div>
        <div class="row">
            <div class="col-md-offset-4 col-md-4 text-centered">
                <a href="{{fb_link}}"><img class="facebook-logo" src="{% static 'image/fb.png'%}" alt="facebook"></a>
                <p>{% trans "Retrouvez nous sur facebook" %}</p>
            </div>
        </div>
    </div>
</div>
 <div class="showcase margin-top">
     <div class="container">
         <span class="text-in-black-box">{% trans "Les vidéos movi't" %}</span>
         <div class="row">
             <div id="myCarousel" class="carousel slide revealOnScroll" data-ride="carousel">
                  <!-- Indicators -->
                  <ol class="carousel-indicators">
                    {% for slide in slides %}
                        <li data-target="#myCarousel" data-slide-to="{{forloop.counter|add:-1}}" {% if forloop.first %}class="active"{% endif %}></li>
                    {% endfor %}
                  </ol>

                  <!-- Wrapper for slides -->
                  <div class="carousel-inner">
                  {% for slide in slides %}

                    <div class="item {% if forloop.first %} active {% endif %}">
                        <img src="{{slide.image.url}}" alt="{{slide.name}}">
                        <div class="carousel-caption">
                            <h3>{{slide.name}}</h3>
                            <p>{{slide.description}}</p>
                        </div>
                    </div>

                  {% endfor %}
                  </div>

                  <!-- Left and right controls -->
                  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
            </div>
        </div>
 </div>
 <div class="container margin-top margin-bottom partners">
     <h2 class="intro-title">{% trans "Nos partenaires :" %}</h2><hr>
        {% for partner in partners %}
        {% if forloop.first or forloop.counter|add:-1|divisibleby:3 %}
        <div class="row">
        {% endif %}
            <div class="col-md-4 text-centered revealOnScroll" style="transition-delay: {{partner.1}}s;">
                <a href="{{partner.0.website}}"><img src="{{ partner.0.logo.url }}" alt="{{partner.0.name}}" class="logo"></a>
                <h3>{{partner.0.name}}</h3>
            </div>
        {% if forloop.last or forloop.counter|divisibleby:3 %}
    </div>
        {%endif%}
        {% endfor %}
</div>

 {% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'js/modernizr.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js'%}"></script>
    <script type="text/javascript">
        $(function() {

          var $window           = $(window),
              win_height_padded = $window.height() * 1.1,
              isTouch           = Modernizr.touch;

          if (isTouch) { $('.revealOnScroll').removeClass('animated'); }

          $window.on('scroll', revealOnScroll);

          function revealOnScroll() {
            var scrolled = $window.scrollTop(),
                win_height_padded = $window.height() * 1.1;

            // Showed...
            $(".revealOnScroll").each(function () {
              var $this     = $(this),
                  offsetTop = $this.offset().top;

              if (scrolled + win_height_padded > offsetTop) {
                  $this.removeClass('revealOnScroll');
                  $this.addClass('animated');
              }
            });

           $(".animated").each(function (index) {
              var $this     = $(this),
                  offsetTop = $this.offset().top;
              if (scrolled + win_height_padded < offsetTop) {
                $(this).addClass('revealOnScroll')
                $(this).removeClass('animated')
              }
            });
          }

          revealOnScroll();
        });
    </script>
{% endblock %}

pages/templates/pages/list_vids.html
{% extends "pages/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{prod.name}}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/list-vid.css'%}">
{% endblock %}

{% block content %}
<div class="wrapper">
<div class="container">
    <div class="row text-centered">
        <h1 class="title"><span class="test">{% trans "Liste des vidéos : " %}{{prod.name}}</span></h1>
    </div>
    <div class="row margin-bottom">
        <div class="col-md-12 text">
            <p>{{prod.description|linebreaks}}</p>
        </div>
    </div>
    {% for videos in sorted %}
        <h2 class="title">{{videos.0.year}}</h2>
        {% for video in videos %}
            {% if forloop.first or forloop.counter|add:-1|divisibleby:3%}
            <div class="row">
            {% endif %}
                <div class="col-md-4 video-link">
                    <a href="{% url 'pages:video' video.id %}">
                        <img class="thumbnail" src="{{video.thumbnail.url}}" alt="{{video.name}}">
                        <span class="video-name">{{video.name}}</span>
                    </a>
                </div>
            {% if forloop.last or forloop.counter|divisibleby:3%}
            </div>
            {% endif %}
        {% endfor %}
    {% endfor %}
    {% if has_next or has_previous %}
    <div class="row margin-top margin-bottom">
        <div class="col-md-12 text">
            {% if has_previous %} <a href="{% url 'pages:prod-page' prod.id previous %}" class="nav-link-pagin"><span class="fa fa-chevron-circle-left"></span> {% trans "Précédent" %}</a> {% endif %}
            {% if has_next %} <a href="{% url 'pages:prod-page' prod.id next %}" class="nav-link-pagin" style="float: right">{% trans "Suivant" %} <span class="fa fa-chevron-circle-right"></span></a> {% endif %}
        </div>
    </div>
    {% else %}
    <div class="row margin-bottom">

    </div>
    {% endif %}
</div>
</div>

{% endblock %}

pages/templates/pages/page.html
{% extends "pages/base.html" %}
{% load static %}
{% load i18n %}

{% block css %}
<!--<link rel="stylesheet" href="{% static 'css/page.css'%}">-->
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="row text-centered">
                <h2 class="title">{{page.title}}</h2>
            </div>
            <div class="row text">
                {{page.content|safe}}
            </div>
        </div>
    </div>
</div>
{% endblock %}

pages/templates/pages/team.html
{% extends "pages/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "L'équipe" %}{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/team.css'%}">
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="container">
        <div class="row">
            {% for year in years %}
                <div class="col-xs-2 text-centered margin-top">
                    <p class="text year-link"><a href="{% url 'pages:specific-team' year%}">{{year}}</a></p>
                </div>
            {% endfor %}
        </div>
        <div class="row text-centered">
            <h1 class="title"><span class="test">{% trans "Équipe Movi't " %}{{team.year}}</span></h1>
        </div>
        <div class="row text-centered">
            <img class="photo" src="{{team.group_photo.url}}" alt="{{team.year}}">
        </div>
        <div class="row">
            <p class="text">{% trans "Président(s) :" %}</p>
        </div>
        {% for prez in prezs %}
        {% if forloop.first or forloop.counter|add:-1|divisibleby:4 %}
        <div class="row">
        {% endif %}
            <div class="col-md-3 text-centered">
                {% if prez.photo %}
                    <img class="photo" src="{{prez.photo.url}}" alt="{{prez.last_name}}">
                {% else %}
                    <img class="photo" src="{% static 'image/logo_carre.png' %}" alt="{{prez.last_name}}">
                {% endif %}
                <p class="text description">
                    <span class="bold">{{prez.last_name}}<br />{{prez.first_name}}</span><br />{{prez.fonction}}
                </p>
            </div>
        {% if forloop.last or forloop.counter|divisibleby:4 %}
        </div>
        {% endif %}
        {% endfor %}
        <div class="row">
            <p class="text">{% trans "Membres :" %}</p>
        </div>
        {% for member in members %}
        {% if forloop.first or forloop.counter|add:-1|divisibleby:4 %}
        <div class="row">
        {% endif %}
            <div class="col-md-3 text-centered">
                {% if member.photo %}
                    <img class="photo" src="{{member.photo.url}}" alt="{{member.last_name}}">
                {% else %}
                    <img class="photo" src="{% static 'image/logo_carre.png' %}" alt="{{member.last_name}}">
                {% endif %}
                <p class="text description">
                    <span class="bold">{{member.last_name}}<br />{{member.first_name}}</span><br />{{member.fonction}}
                </p>
            </div>
        {% if forloop.last or forloop.counter|divisibleby:4 %}
        </div>
        {% endif %}
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

pages/templates/pages/video.html
{% extends "pages/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{{video.name}}{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/video.css'%}">
<link rel="stylesheet" href="{% static 'css/video-js.css'%}">
<script type="text/javascript" src="{% static 'js/videojs.min.js' %}"></script>
{% endblock %}

{% block content %}
<div class="wrapper">
<div class="container">
    <div class="row text-centered">
        <h1 class="title"><span class="test">{{video.name}}</span></h1>
    </div>
    <div class="row text-centered">
        <div class="col-md-12 video">
            <p class="text date" >{% trans "Mise en ligne le " %}{{video.date|date:"d M Y"}}{% trans " à " %}{{video.date|date:"H:m"}} | <span class="bold">Année {{video.year}}</span></p>
            <video id="my-video" class="video-js" controls preload="auto" poster="{{video.thumbnail.url}}" data-setup="{}">
                <source src="{{video.video.url}}" type='video/mp4'>
                <p class="vjs-no-js">
                  To view this video please enable JavaScript, and consider upgrading to a web browser that
                  <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
                </p>
            </video>
        </div>
    </div>
    <div class="row margin-bottom">
        <div class="col-md-12 margin-top">
            <div class="text">
                <p style="float: right">Vues : {{video.count}}</p>
                <h3>Description :</h3>
                <p>{{video.description|linebreaks}}</p>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        window.HELP_IMPROVE_VIDEOJS = false;
    </script>
{% endblock %}